config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  namespace :admin do
    root "dashboard#index"
    resources :users, except: [:create, :new, :show]
    resources :categories
    resources :words
  end

  resources :users
  resources :relationships, only: [:create, :destroy, :index]
  resources :categories, only: [:index, :show]
  resources :words, only: [:index]
  resources :lessons, except: [:destroy, :new, :edit]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @feed_items = Activity.feed(current_user.following_ids, current_user.id)
      .order_by_time.paginate(page: params[:page]).per_page Settings.page_size if logged_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<% provide :title, t(:about) %>
<h1><%= t :about %></h1>

app/views/static_pages/contact.html.erb
<% provide :title, t(:contact) %>
<h1><%= t :contact %></h1>

app/views/static_pages/home.html.erb
<div class="fluid-container dn-photo-border-content">
  <div class="dn-photo-cover">
    <% if logged_in? %>
      <div class="dn-photo-cover-content-user">
        <%= image_tag current_user.avatar.url, class: "dn-front-home-img" %>
        <div class="dn-cover-title">
          <div class="dn-title-content">
            <h1><%= link_to current_user.name, user_path(current_user) %></h1>
          </div>
        </div>
      </div>     
    <% else %>
      <div class="dn-front-home-btn">      
        <%= link_to t(:login), login_path,
          class: "btn dn-btn-login hvr-bounce-to-right" %>
        <%= link_to t(:signup), signup_path,
          class: "btn dn-btn-signup hvr-bounce-to-left" %> 
      </div>
      <div class="dn-photo-cover-content"></div>
    <% end %>
    <div class="dn-cover-full"></div>
  </div>
</div>
<% if logged_in? %>
  <div class="row ">
    <div class="col-md-8 col-md-offset-2 dn-front-group">
      <% if @feed_items.any? %>
        <ul class="activities">
          <%= render @feed_items %>
        </ul>
        <%= will_paginate @feed_items %>
      <% end %>
    </div>
  </div>
<% end %>