config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  namespace :admin do
    root "dashboard#index"
    resources :users, except: [:create, :new, :show]
    resources :categories
    resources :words
  end

  resources :users
  resources :relationships, only: [:create, :destroy, :index]
  resources :categories, only: [:index, :show]
  resources :words, only: [:index]
  resources :lessons, except: [:destroy, :new, :edit]

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  
  has_many :word_answers, dependent: :destroy
  has_many :results

  validates :content, presence: true, length: {maximum: 20}
  validate :check_answers

  accepts_nested_attributes_for :word_answers,
    reject_if: lambda {|a| a[:content].blank?}, allow_destroy: true

  scope :category, ->category_id{where category_id: category_id}
  scope :learned, ->(user_id){select("distinct content")
    .joins(results: :lesson).where lessons: {user_id: user_id}}
  scope :not_learn, ->user_id{where("id not in (select word_id from results 
    where lesson_id in (select id from lessons where user_id = #{user_id}))")}
  scope :all_word, ->user_id{}

  private
  def check_answers
    correct_answer = word_answers.select {|word_answer| word_answer.is_correct?}
    errors.add(:word_answers, I18n.t(:must_check)) if correct_answer.empty?
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  layout "admin/application"
  before_action :require_admin
  before_action :find_word, except: [:index, :new, :create]

  helper_method :sort_column, :sort_direction

  def index
    @categories = Category.all
    @words = Word.all
    @words = @words.category(params[:category]) if params[:category].present?
    @words = @words.order(sort_column + " " + sort_direction)
      .paginate(page: params[:page]).per_page Settings.page_size
  end
  
  def show
  end

  def new
    @categories = Category.all
    @word = Word.new
    Settings.number_of_answers.times {@word.word_answers.build}
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t :created_word
      redirect_to admin_word_path(@word)
    else
      @categories = Category.all
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t :word_updated
      redirect_to admin_word_path @word
    else
      render :edit
   end
  end

  def destroy
    @word.destroy
    flash[:success] = t :destroy_sucess
    redirect_to admin_words_path
  end

  private
  def word_params
    params.require(:word).permit :content, :category_id,
      word_answers_attributes: [:id, :content, :is_correct, :_destroy]
  end
  
  def find_word
    @word = Word.find_by_id params[:id]
    if @word.nil?
      flash[:danger] = t :word_fails
      redirect_to admin_words_path
    end
  end

  def sort_column
    Word.column_names.include?(params[:sort]) ? params[:sort] : "content"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user, only: :index

  def index
    @categories = Category.all
    @words = if params[:category_id].nil? ||
      params[:category_id].empty? && params[:word_type].nil?
      params[:word_type] = "all_word"
      Word.all
    elsif params[:category_id].empty?
      Word.all.send "#{type}", current_user.id
    else
      category = @categories.find_by id: params[:category_id]
      words = category.words
      @words = words.send "#{type}", current_user.id
    end
    @words = @words.paginate(page: params[:page]).per_page Settings.page_size
  end

  private
  def type
    params[:word_type] == Settings["not_learn"] ? Settings["not_learn"] : params[:word_type]
  end
end

app/helpers/words_helper.rb
module WordsHelper
  def add_answer_link name, association, target
    content_tag :spam, "<a>#{name}</a>".html_safe,
      class: "add_answer",
      "data-association": association,
      target: target
  end

  def new_fields_template f, association, options={}
    options[:object] ||= f.object.class.reflect_on_association(association).klass.new
    options[:partial] ||= association.to_s.singularize + "_fields"
    options[:template] ||= association.to_s + "_fields"
    options[:f] ||= :f

    tmpl = content_tag :div, id:"#{options[:template]}" do
      tmpl = f.fields_for association, options[:object], child_index: "new_#{association}" do |b|
        render partial: options[:partial], locals: {f: b}
      end
    end
    tmpl = tmpl.gsub /(?<!\n)\n(?!\n)/, " "
    "<script> var #{options[:template]} = '#{tmpl.to_s}' </script>".html_safe
	end

  def word_answer_class word_answer
    word_answer.is_correct? ? "correct_answer" : "well"
  end
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <div class="fields dn-cate-new">
    <%= f.label :category, class: "dn-admin-word-label" %>
    <%= f.select :category_id,
      @categories.collect {|category| [category.title, category.id]} %>
    <p>
      <%= f.label :content %><br />
      <%= f.text_field :content, class: "form-control dn-admin-word-content" %>
    </p>
    <div id="word_answers">
      <%= f.fields_for :word_answers do |builder| %>
        <%= render "word_answer_fields", f: builder %>
      <% end %>
    </div>
    <%= add_answer_link t(:new_answer), :word_answers, "word_answers" %>
    <%= new_fields_template f, :word_answers %>
    <p><%= f.submit t(:create), class: "btn btn-primary dn-admin-word-btn" %></p>
  </div>
<% end %>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= link_to word.content, admin_word_path(word) %></td>
  <td><%= link_to word.category.title,
    admin_category_path(word.category) %></td>
  <td><%= word.created_at.strftime t(:time_type) %></td>
  <td><%= word.updated_at.strftime t(:time_type) %></td>
  <td class="dn-action-padding">
    <%= link_to t(:edit), edit_admin_word_path(word), class: "btn btn-primary" %>
    <%= link_to t(:delete), [:admin, word], method: :delete, data: {confirm: t(:sure)},
      class: "btn btn-danger btn-primary" %>
  </td>
</tr>

app/views/admin/words/_word_answer_fields.html.erb
<ul class="removable col-md-6">
  <%= f.label :content, t(:answer) %>
  <li class="input-group">
    <span class="input-group-addon dn-admin-addon">
      <%= f.label :is_correct, class: "checkbox inline dn-admin-word-check" do %>
        <%= f.check_box :is_correct, class: "chb dn-admin-wordanswer-check" %>
      <% end %>
    </span>
    <%= f.text_field :content, class: "form-control", placeholder: I18n.t(:check_true) %>
  </li>
  <%= f.hidden_field :_destroy %>
  <%= link_to t(:remove), "#", class: "remover_link"  %>
</ul>

app/views/admin/words/edit.html.erb
<% provide :title, t(:edit_word) %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 form-group">
    <%= form_for [:admin, @word] do |f| %>
      <div class="fields">
        <p>
          <%= f.label :content %><br />
          <%= f.text_field :content, class: "form-control" %>
        </p>
        <div id="word_answers">
          <%= f.fields_for :word_answers do |builder| %>
            <%= render "word_answer_fields", f: builder %>
          <% end %>
        </div>
        <%= add_answer_link t(:new_answer), :word_answers, "word_answers" %>
        <%= new_fields_template f, :word_answers %>
        <p><%= f.submit t(:save_change) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t(:all_words) %>
<h1><%= t :all_words %></h1>

<%= form_tag admin_words_path, method: :get, class: "dn-admin-cate-form" do %>
  <%= label_tag :category %>
  <%= select_tag :category, options_from_collection_for_select(@categories, "id", "title"),
    include_blank: true, class: "btn btn-default dn-admin-cate-select" %>
  <button class="btn" type="submit">
    <span class="fa fa-search"></span>
  </button>
  <%= link_to t(:create), new_admin_word_path, class: "btn btn-primary pull-right btn-sm" %>
<% end %>

<div class="panel-body">
  <table class="table pretty">
    <thead>
      <th><%= sortable t "word.content" %></th>
      <th><%= sortable t "word.category" %></th>
      <th><%= t "word.created_at" %></th>
      <th><%= t "word.update_at" %></th>
      <th class="action" width=<%= Settings.th_width %>><%= t :action %></th>
    </thead>
    <% if @words.blank? %>
      <td><i><b><%= t :no_word_in_category %></b></i></td>
    <% else %>
      <%= render @words %>
    <% end %>
  </table>
</div>
<%= will_paginate %>

app/views/admin/words/new.html.erb
<h1><%= t :new_word %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2 form-group">
   <%= render "form" %>
  </div>
</div>

app/views/admin/words/show.html.erb
<% provide :title, t(:show_word) %>
<div class="word">
  <h4><b><%= t :category %>: <%= @word.category.title %></b></h4>
  <h1><%= @word.content %></h1>
  <div class="answers_field">
    <ul>
      <%= render @word.word_answers %>
    </ul>
  </div>
</div>