config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  namespace :admin do
    root "dashboard#index"
    resources :users, except: [:create, :new, :show]
    resources :categories
    resources :words
  end

  resources :users
  resources :relationships, only: [:create, :destroy, :index]
  resources :categories, only: [:index, :show]
  resources :words, only: [:index]
  resources :lessons, except: [:destroy, :new, :edit]

end

app/views/layouts/admin/_footer.html.erb
<footer class="main-footer">
  <strong><%= t "admin.footer" %></strong>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="main-header">
  <a href="/" class="logo">
    <span class="logo-mini"><b><%= t "admin.p1" %></b></span>
    <span class="logo-lg"><b><%= t "admin.project1" %></b></span>
  </a>

  <nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"></a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_user.avatar.url, class: "user-image" %>
            <span class="hidden-xs"><%= current_user.name %></span>
            <ul class="dropdown-menu dn-dropdown-menu">
              <li>
                <%= link_to t(:logout), logout_path, method: :delete %>
              </li>
            </ul>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li class="active">
        <%= link_to admin_root_path do %> 
          <i class="glyphicon glyphicon-dashboard"></i> 
          <span><%= t "admin.dashbord" %></span>
        <% end %>
      </li>

      <li>
        <%= link_to admin_users_path do %>
          <i class="glyphicon glyphicon-user"></i> 
          <span><%= t :show_user %></span>
        <% end %>  
      </li>

      <li class="treeview">
        <a href="#">
          <i class="glyphicon glyphicon-tasks"></i>
          <span><%= t "admin.category" %></span> 
          <i class="glyphicon glyphicon-chevron-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><%= link_to t(:index), admin_categories_path %></li>
          <li><%= link_to t(:create), new_admin_category_path %></li>
        </ul>
      </li>

      <li class="treeview">
        <a href="#">
          <i class="glyphicon glyphicon-list-alt"></i>
          <span><%= t "admin.word" %></span> 
          <i class="glyphicon glyphicon-chevron-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><%= link_to t(:index), admin_words_path %></li>
          <li><%= link_to t(:create), new_admin_word_path %></li>
        </ul>
      </li>     
    </ul>
  </section>
</aside>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= stylesheet_link_tag "application",
      media: "all","data-turbolinks-track": true %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <%= render "layouts/admin/header" %>
      <%= render "layouts/admin/sidebar" %>

      <div class="content-wrapper dn-content">
        <section class="content">
          <%= yield %>
        </section>
      </div>
      <%= render "layouts/admin/footer" %>
      <div class="control-sidebar-bg"></div>
    </div>
  </body>
</html>