config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  namespace :admin do
    root "dashboard#index"
    resources :users, except: [:create, :new, :show]
    resources :categories
    resources :words
  end

  resources :users
  resources :relationships, only: [:create, :destroy, :index]
  resources :categories, only: [:index, :show]
  resources :words, only: [:index]
  resources :lessons, except: [:destroy, :new, :edit]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <span><%= t :theform %></span> <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to relationships_path user_id: @user, relationship: "following" do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t :following %>
  <% end %>
  <%= link_to relationships_path user_id: @user, relationship: "followers" do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t :followers %>
  <% end %>
</div>